name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "43 2 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_LINES_OF_CODE: "TRUE"
          IGNORED_REPOS: "smart-house, tech-flames, braven-documentation, fire-department-2021-documnetation, chupacabra-documnetation, lathraea-rhodopaea-docs"
